spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hair_customized_ai}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hair}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:qowngus}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
